from django.urls import path


from .views import (
    AdminDashboardIndexView,
    CountriesListView,
    CountryCreateView,
    CountryDeleteView,
    CountryUpdateView,
    IncomeInfoCreateView,
    IncomeInfoDeleteView,
    IncomeInfoListView,
    IncomeInfoUpdateView,
    KeysListView,
    LogsListView,
    PricesCreateView,
    PricesDeleteView,
    PricesListView,
    PricesUpdateView,
    ServerCreateView,
    ServerDeleteView,
    ServersListView,
    ServerDetailView,
    ServerInitActionView,
    ServerUpdateView,
    ReferralSettingsCreateView,
    ReferralSettingsDeleteView,
    ReferralSettingsListView,
    ReferralSettingsUpdateView,
    ReferralSpecialOfferCreateView,
    ReferralSpecialOfferCRUDListView,
    ReferralSpecialOfferDeleteView,
    ReferralSpecialOfferUpdateView,
    ReferralTransactionCreateView,
    ReferralTransactionCRUDListView,
    ReferralTransactionDeleteView,
    ReferralTransactionUpdateView,
    SiteNotificationCreateView,
    SiteNotificationDeleteView,
    SiteNotificationsListView,
    SiteNotificationStateCreateView,
    SiteNotificationStateDeleteView,
    SiteNotificationStatesListView,
    SiteNotificationStateUpdateView,
    SiteNotificationUpdateView,
    TelegramBotCreateView,
    TelegramBotCRUDListView,
    TelegramBotDeleteView,
    TelegramBotUpdateView,
    TelegramReferralCreateView,
    TelegramReferralCRUDListView,
    TelegramReferralDeleteView,
    TelegramReferralUpdateView,
    TelegramMessageCreateView,
    TelegramMessageDeleteView,
    TelegramMessagesListView,
    TelegramMessageUpdateView,
    TelegramUserCRUDListView,
    TelegramUserCreateView,
    TelegramUserDeleteView,
    TelegramUserUpdateView,
    TransactionDetailView,
    TransactionCreateView,
    TransactionCRUDListView,
    TransactionDeleteView,
    TransactionUpdateView,
    TransactionsListView,
    UserProfileCRUDListView,
    UserProfileCreateView,
    UserProfileDeleteView,
    UserProfileUpdateView,
    UserDetailView,
    UsersListView,
    VpnKeyCRUDListView,
    VpnKeyCreateView,
    VpnKeyDeleteView,
    VpnKeyUpdateView,
)


app_name = "admindashboardx"

urlpatterns = [
    path("", AdminDashboardIndexView.as_view(), name="index"),
    path("users/", UsersListView.as_view(), name="users"),
    path("users/<int:telegram_user_id>/", UserDetailView.as_view(), name="user_detail"),
    path("transactions/", TransactionsListView.as_view(), name="transactions"),
    path("transactions/<int:tx_id>/", TransactionDetailView.as_view(), name="transaction_detail"),
    path("logs/", LogsListView.as_view(), name="logs"),
    path("servers/", ServersListView.as_view(), name="servers"),
    path("servers/create/", ServerCreateView.as_view(), name="server_create"),
    path("servers/<int:server_id>/", ServerDetailView.as_view(), name="server_detail"),
    path("servers/<int:server_id>/edit/", ServerUpdateView.as_view(), name="server_update"),
    path("servers/<int:server_id>/delete/", ServerDeleteView.as_view(), name="server_delete"),
    path("servers/<int:server_id>/init/", ServerInitActionView.as_view(), name="server_init"),
    path("countries/", CountriesListView.as_view(), name="countries"),
    path("countries/create/", CountryCreateView.as_view(), name="country_create"),
    path("countries/<int:country_id>/edit/", CountryUpdateView.as_view(), name="country_update"),
    path("countries/<int:country_id>/delete/", CountryDeleteView.as_view(), name="country_delete"),
    path("prices/", PricesListView.as_view(), name="prices"),
    path("prices/create/", PricesCreateView.as_view(), name="prices_create"),
    path("prices/<int:item_id>/edit/", PricesUpdateView.as_view(), name="prices_update"),
    path("prices/<int:item_id>/delete/", PricesDeleteView.as_view(), name="prices_delete"),
    path("telegram-messages/", TelegramMessagesListView.as_view(), name="telegram_messages"),
    path("telegram-messages/create/", TelegramMessageCreateView.as_view(), name="telegram_message_create"),
    path("telegram-messages/<int:item_id>/edit/", TelegramMessageUpdateView.as_view(), name="telegram_message_update"),
    path("telegram-messages/<int:item_id>/delete/", TelegramMessageDeleteView.as_view(), name="telegram_message_delete"),
    path("site-notifications/", SiteNotificationsListView.as_view(), name="site_notifications"),
    path("site-notifications/create/", SiteNotificationCreateView.as_view(), name="site_notification_create"),
    path("site-notifications/<int:item_id>/edit/", SiteNotificationUpdateView.as_view(), name="site_notification_update"),
    path("site-notifications/<int:item_id>/delete/", SiteNotificationDeleteView.as_view(), name="site_notification_delete"),
    path("site-notification-states/", SiteNotificationStatesListView.as_view(), name="site_notification_states"),
    path("site-notification-states/create/", SiteNotificationStateCreateView.as_view(), name="site_notification_state_create"),
    path("site-notification-states/<int:item_id>/edit/", SiteNotificationStateUpdateView.as_view(), name="site_notification_state_update"),
    path("site-notification-states/<int:item_id>/delete/", SiteNotificationStateDeleteView.as_view(), name="site_notification_state_delete"),
    path("income-info/", IncomeInfoListView.as_view(), name="income_info"),
    path("income-info/create/", IncomeInfoCreateView.as_view(), name="income_info_create"),
    path("income-info/<int:item_id>/edit/", IncomeInfoUpdateView.as_view(), name="income_info_update"),
    path("income-info/<int:item_id>/delete/", IncomeInfoDeleteView.as_view(), name="income_info_delete"),
    path("referral-settings/", ReferralSettingsListView.as_view(), name="referral_settings"),
    path("referral-settings/create/", ReferralSettingsCreateView.as_view(), name="referral_settings_create"),
    path("referral-settings/<int:item_id>/edit/", ReferralSettingsUpdateView.as_view(), name="referral_settings_update"),
    path("referral-settings/<int:item_id>/delete/", ReferralSettingsDeleteView.as_view(), name="referral_settings_delete"),
    path("vpnkey-crud/", VpnKeyCRUDListView.as_view(), name="vpnkey_crud"),
    path("vpnkey-crud/create/", VpnKeyCreateView.as_view(), name="vpnkey_create"),
    path("vpnkey-crud/<int:item_id>/edit/", VpnKeyUpdateView.as_view(), name="vpnkey_update"),
    path("vpnkey-crud/<int:item_id>/delete/", VpnKeyDeleteView.as_view(), name="vpnkey_delete"),
    path("telegram-users-crud/", TelegramUserCRUDListView.as_view(), name="telegram_users_crud"),
    path("telegram-users-crud/create/", TelegramUserCreateView.as_view(), name="telegram_user_create"),
    path("telegram-users-crud/<int:item_id>/edit/", TelegramUserUpdateView.as_view(), name="telegram_user_update"),
    path("telegram-users-crud/<int:item_id>/delete/", TelegramUserDeleteView.as_view(), name="telegram_user_delete"),
    path("user-profiles-crud/", UserProfileCRUDListView.as_view(), name="user_profile_crud"),
    path("user-profiles-crud/create/", UserProfileCreateView.as_view(), name="user_profile_create"),
    path("user-profiles-crud/<int:item_id>/edit/", UserProfileUpdateView.as_view(), name="user_profile_update"),
    path("user-profiles-crud/<int:item_id>/delete/", UserProfileDeleteView.as_view(), name="user_profile_delete"),
    path("telegram-referrals-crud/", TelegramReferralCRUDListView.as_view(), name="telegram_referral_crud"),
    path("telegram-referrals-crud/create/", TelegramReferralCreateView.as_view(), name="telegram_referral_create"),
    path("telegram-referrals-crud/<int:item_id>/edit/", TelegramReferralUpdateView.as_view(), name="telegram_referral_update"),
    path("telegram-referrals-crud/<int:item_id>/delete/", TelegramReferralDeleteView.as_view(), name="telegram_referral_delete"),
    path("referral-transactions-crud/", ReferralTransactionCRUDListView.as_view(), name="referral_transaction_crud"),
    path("referral-transactions-crud/create/", ReferralTransactionCreateView.as_view(), name="referral_transaction_create"),
    path("referral-transactions-crud/<int:item_id>/edit/", ReferralTransactionUpdateView.as_view(), name="referral_transaction_update"),
    path("referral-transactions-crud/<int:item_id>/delete/", ReferralTransactionDeleteView.as_view(), name="referral_transaction_delete"),
    path("referral-special-offers-crud/", ReferralSpecialOfferCRUDListView.as_view(), name="referral_special_offer_crud"),
    path("referral-special-offers-crud/create/", ReferralSpecialOfferCreateView.as_view(), name="referral_special_offer_create"),
    path("referral-special-offers-crud/<int:item_id>/edit/", ReferralSpecialOfferUpdateView.as_view(), name="referral_special_offer_update"),
    path("referral-special-offers-crud/<int:item_id>/delete/", ReferralSpecialOfferDeleteView.as_view(), name="referral_special_offer_delete"),
    path("telegram-bots-crud/", TelegramBotCRUDListView.as_view(), name="telegram_bot_crud"),
    path("telegram-bots-crud/create/", TelegramBotCreateView.as_view(), name="telegram_bot_create"),
    path("telegram-bots-crud/<int:item_id>/edit/", TelegramBotUpdateView.as_view(), name="telegram_bot_update"),
    path("telegram-bots-crud/<int:item_id>/delete/", TelegramBotDeleteView.as_view(), name="telegram_bot_delete"),
    path("transactions-crud/", TransactionCRUDListView.as_view(), name="transaction_crud"),
    path("transactions-crud/create/", TransactionCreateView.as_view(), name="transaction_create"),
    path("transactions-crud/<int:item_id>/edit/", TransactionUpdateView.as_view(), name="transaction_update"),
    path("transactions-crud/<int:item_id>/delete/", TransactionDeleteView.as_view(), name="transaction_delete"),
    path("keys/", KeysListView.as_view(), name="keys"),
]
