# Generated by Django 4.2.18 on 2025-03-18 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название страны')),
                ('preset_id', models.IntegerField(blank=True, null=True, verbose_name='preset_id')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активно')),
                ('name_for_app', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name for app')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_amount', models.IntegerField(blank=True, null=True, verbose_name='Количество сервероа')),
                ('time_web_api_key', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Time Web API Token')),
                ('payment_system_api_key', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ukassa token')),
                ('cloud_init', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Cloud Init')),
                ('data_limit', models.BigIntegerField(blank=True, null=True, verbose_name='Data Limit GB')),
                ('os_id', models.IntegerField(blank=True, null=True, verbose_name='OS id')),
                ('software_id', models.IntegerField(blank=True, null=True, verbose_name='Software id')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='IncomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общий баланс проекта')),
                ('user_balance_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общий баланс всех пользователей')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_1_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ru_3_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ru_6_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ru_12_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pol_1_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pol_3_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pol_6_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pol_12_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('neth_1_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('neth_3_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('neth_6_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('neth_12_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kaz_1_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kaz_3_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kaz_6_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kaz_12_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='price for 1 month')),
                ('price_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='price for 3 month')),
                ('price_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='price for 6 month')),
                ('price_4', models.PositiveIntegerField(blank=True, null=True, verbose_name='price for 12 month')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 1 Percentage')),
                ('level_2_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 2 Percentage')),
                ('level_3_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 3 Percentage')),
                ('level_4_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 4 Percentage')),
                ('level_5_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 5 Percentage')),
            ],
            options={
                'verbose_name': 'Настройки Рефералов',
                'verbose_name_plural': 'Настройки Рефералов',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Хостинг')),
                ('ip_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='IP Address')),
                ('user', models.CharField(blank=True, default='root', max_length=1000, null=True, verbose_name='Пользователь')),
                ('password', models.CharField(blank=True, default='<PASSWORD>', max_length=1000, null=True, verbose_name='Пароль')),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена аренды в месяц')),
                ('max_keys', models.IntegerField(blank=True, default=200, editable=False, null=True, verbose_name='Лимит ключей')),
                ('keys_generated', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ключей сгенерировано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Сервер Активен')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('api_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='API URL')),
                ('cert_sha256', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Certificate SHA256')),
                ('script_out', models.JSONField(blank=True, null=True, verbose_name='Script Out Info JSON')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Сервер Активирован для Outline (не трогать)')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'VPN сервер',
                'verbose_name_plural': 'VPN сервера',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='TG BOT Token')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('payment_system_api_key', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Payment system token')),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bot',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('not_sent', 'Не отправлено')], default='not_sent', max_length=20, verbose_name='Статус рассылки')),
                ('send_to_subscribed', models.BooleanField(default=False, verbose_name='Отправить подписанным')),
                ('send_to_notsubscribed', models.BooleanField(default=False, verbose_name='Отправить не подписанным')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Отправлено пользователям')),
            ],
            options={
                'verbose_name': 'Сообщение Telegram',
                'verbose_name_plural': 'Сообщения Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Присоединился')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='user_id')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('photo_url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Photo URL')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Забанен')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс для активации подписок')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Доход от реферальной программы')),
                ('subscription_status', models.BooleanField(default=False, verbose_name='Статус подписки')),
                ('subscription_expiration', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания подписки')),
                ('data_limit', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Data Limit')),
                ('top_up_balance_listener', models.BooleanField(default=False, verbose_name='Top up balance listener')),
                ('withdrawal_listener', models.BooleanField(default=False, verbose_name='Withdrawal listener')),
            ],
            options={
                'verbose_name': 'Пользователь ТГ',
                'verbose_name_plural': 'Пользователи ТГ',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество')),
                ('status', models.BooleanField(default=False, verbose_name='Статус запроса о выводе средств')),
                ('currency', models.CharField(blank=True, max_length=1000, verbose_name='Валюта')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на вывод средств',
                'verbose_name_plural': 'Запросы на вывод средств',
            },
        ),
        migrations.CreateModel(
            name='VpnKey',
            fields=[
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('key_id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='Key ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Method')),
                ('access_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Access URL')),
                ('used_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Used Bytes')),
                ('data_limit', models.BigIntegerField(blank=True, null=True, verbose_name='Data Limit')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.server', verbose_name='Сервер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'VPN Ключ',
                'verbose_name_plural': 'VPN Ключи',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='bot.telegramuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('side', models.CharField(blank=True, choices=[('Приход средств', 'Приход средств'), ('Вывод средств', 'Вывод средств')], max_length=100, null=True, verbose_name='Направление транзакции')),
                ('description', models.CharField(blank=True, choices=[('1 MONTH', '1 месяц'), ('3 MONTH', '3 месяца'), ('6 MONTH', '6 месяцев'), ('1 YEAR', '1 год')], default=None, max_length=255, null=True, verbose_name='Описание платежа')),
                ('payment_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID платежа')),
                ('paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплачено')),
                ('status', models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('succeeded', 'Успешно'), ('canceled', 'Отменено'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('captured', 'Захвачено')], default='pending', max_length=50, null=True, verbose_name='Статус')),
                ('income_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Доходы', to='bot.incomeinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(blank=True, choices=[('TRACE', 'TRACE'), ('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('FATAL', 'FATAL'), ('SUCCESS', 'SUCCESS')], max_length=50, null=True, verbose_name='LOG LEVEL')),
                ('message', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='TelegramReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='bot.telegramuser', verbose_name='Зарегистрирован по ссылке')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_referrals', to='bot.telegramuser', verbose_name='Поделился ссылкой')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
