# Generated by Django 4.2.18 on 2025-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='marzban_api_key',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='MB token'),
        ),
    ]
