# Generated by Django 4.2.18 on 2025-03-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegrambot_marzban_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnkey',
            name='protocol',
            field=models.CharField(blank=True, default='outline', max_length=255, null=True, verbose_name='Protocol'),
        ),
    ]
