# Generated by Django 4.2.18 on 2025-03-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_vpnkey_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_activated_vless',
            field=models.BooleanField(default=False, verbose_name='Сервер Активирован для VLESS (не трогать)'),
        ),
    ]
