# Generated by Django 4.2.18 on 2025-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_server_is_activated_vless'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='vless_pwd',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='marzban pwd'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='vless_unane',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='marzban username'),
        ),
    ]
