# Generated by Django 4.2.18 on 2025-04-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegrambot_vless_pwd_telegrambot_vless_unane'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='payment_method_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Payment Method ID'),
        ),
    ]
