# Generated by Django 4.2.18 on 2025-04-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegramuser_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='next_payment_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Следующее списание'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='permission_revoked',
            field=models.BooleanField(default=False, verbose_name='Permission Revoked'),
        ),
    ]
