# Generated by Django 4.2.18 on 2025-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegramuser_next_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='permission_revoked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Permission Revoked'),
        ),
    ]
