# Generated by Django 4.2.18 on 2025-04-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_telegramuser_permission_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='price_5',
            field=models.PositiveIntegerField(blank=True, default=20, null=True, verbose_name='price for 3 days trial'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='permission_revoked',
            field=models.BooleanField(default=False, verbose_name='Permission Revoked'),
        ),
    ]
