# Generated by Django 4.2.18 on 2025-05-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_prices_price_5_alter_telegramuser_permission_revoked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='permission_revoked',
            field=models.BooleanField(default=False, verbose_name='Отменил подписку'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Доходы', to='bot.incomeinfo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser', verbose_name='Пользователь'),
        ),
    ]
