# Generated by Django 4.2.18 on 2025-11-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_telegramuser_permission_revoked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Описание платежа'),
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_from', to='bot.telegramuser', verbose_name='От кого')),
                ('user_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_to', to='bot.telegramuser', verbose_name='Кому')),
            ],
        ),
    ]
