# Generated by Django 4.2.18 on 2025-11-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_transaction_description_referraltransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referraltransaction',
            options={'verbose_name': 'Реферальное начисление', 'verbose_name_plural': 'Реферальные начисления'},
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='bot.transaction', verbose_name='Платёж'),
        ),
    ]
