# Generated by Django 4.2.18 on 2025-11-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_referraltransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraltransaction',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='user_to',
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_connection', to='bot.telegramreferral', verbose_name='Реферальная связь'),
        ),
    ]
