# Generated by Django 4.2.18 on 2025-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_remove_referraltransaction_user_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraltransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='join_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Присоединился'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='username'),
        ),
    ]
