# Generated by Django 4.2.18 on 2026-01-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_referraltransaction_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 1 Percentage')),
                ('level_2_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 2 Percentage')),
                ('level_3_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 3 Percentage')),
                ('level_4_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 4 Percentage')),
                ('level_5_percentage', models.IntegerField(blank=True, null=True, verbose_name='Level 5 Percentage')),
            ],
            options={
                'verbose_name': 'Специальное предложение',
                'verbose_name_plural': 'Специальное предложения',
            },
        ),
        migrations.AlterField(
            model_name='incomeinfo',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общий доход проекта'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_activated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сервер Активирован для Outline (не трогать)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_activated_vless',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сервер Активирован для VLESS (не трогать)'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='permission_revoked',
            field=models.BooleanField(default=False, verbose_name='Самостоятельно отменил автоплатёж'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='special_offer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='bot.referralspecialoffer', verbose_name='Специальные проценты'),
        ),
    ]
