# Generated by Django 4.2.18 on 2026-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_referralspecialoffer_alter_incomeinfo_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralspecialoffer',
            options={'verbose_name': 'Специальное предложение', 'verbose_name_plural': 'Специальные предложения'},
        ),
        migrations.AddField(
            model_name='referralspecialoffer',
            name='especial_for_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специально для пользователя (напишите username или Имя)'),
        ),
    ]
