# Generated by Django 4.2.18 on 2026-01-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_referralspecialoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='special_offer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_offers', to='bot.referralspecialoffer', verbose_name='Специальные проценты'),
        ),
    ]
