# Generated by Django 4.2.18 on 2026-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_telegramuser_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralspecialoffer',
            name='level_1_percentage',
            field=models.IntegerField(default=0, verbose_name='Level 1 Percentage'),
        ),
        migrations.AlterField(
            model_name='referralspecialoffer',
            name='level_2_percentage',
            field=models.IntegerField(default=0, verbose_name='Level 2 Percentage'),
        ),
        migrations.AlterField(
            model_name='referralspecialoffer',
            name='level_3_percentage',
            field=models.IntegerField(default=0, verbose_name='Level 3 Percentage'),
        ),
        migrations.AlterField(
            model_name='referralspecialoffer',
            name='level_4_percentage',
            field=models.IntegerField(default=0, verbose_name='Level 4 Percentage'),
        ),
        migrations.AlterField(
            model_name='referralspecialoffer',
            name='level_5_percentage',
            field=models.IntegerField(default=0, verbose_name='Level 5 Percentage'),
        ),
    ]
