# Generated by Django 4.2.18 on 2026-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_referralspecialoffer_level_1_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('YooKassa', 'Юкасса'), ('RoboKassa', 'Робокасса'), ('CryptoBot', 'Криптобот')], default='YooKassa', max_length=255, null=True, verbose_name='Платёжная система'),
        ),
    ]
