# Generated by Django 4.2.18 on 2026-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_transaction_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='site_password_generated',
            field=models.BooleanField(default=False, verbose_name='Пароль для сайта выдан через бота'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('YooKassaBot', 'Юкасса Бот'), ('YooKassaSite', 'Юкасса Сайт'), ('RoboKassaBot', 'Робокасса Бот'), ('RoboKassaSite', 'Робокасса Сайт'), ('CryptoBotBot', 'Криптобот Бот'), ('CryptoBotSite', 'Криптобот Сайт')], default='YooKassaBot', max_length=255, null=True, verbose_name='Платёжная система'),
        ),
    ]
