# Generated by Django 4.2.18 on 2026-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_userprofile_site_password_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='robokassa_recurring_parent_inv_id',
            field=models.CharField(blank=True, default='', help_text='Успешный платёж с Recurring=true; для автосписаний — PreviousInvoiceID.', max_length=32, verbose_name='RoboKassa InvId материнского счёта (рекуррент)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='robokassa_invoice_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='RoboKassa: номер счёта (InvId)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='robokassa_is_recurring_parent',
            field=models.BooleanField(default=False, verbose_name='RoboKassa: материнский рекуррент (Recurring=true)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='robokassa_recurring_previous_inv_id',
            field=models.CharField(blank=True, help_text='У дочернего рекуррентного счёта — InvId материнского платежа.', max_length=32, null=True, verbose_name='RoboKassa: PreviousInvoiceID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, default=None, help_text='ЮKassa: id платежа; RoboKassa: ID операции Robox из OpState при наличии.', max_length=255, null=True, verbose_name='ID операции во внешней ПС'),
        ),
    ]
