# Generated by Django 4.2.18 on 2026-04-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_telegramuser_robokassa_recurring_parent_inv_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Показывать с')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Показывать до')),
            ],
            options={
                'verbose_name': 'Уведомление сайта',
                'verbose_name_plural': 'Уведомления сайта',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='server',
            name='is_activated_vless',
            field=models.BooleanField(default=False, editable=False, verbose_name='MB'),
        ),
        migrations.CreateModel(
            name='SiteNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_notification_id', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='ID последнего прочитанного уведомления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_notification_state', to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние уведомлений пользователя',
                'verbose_name_plural': 'Состояния уведомлений пользователей',
            },
        ),
    ]
