# Generated by Django 4.2.18 on 2026-04-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_sitenotification_alter_server_is_activated_vless_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cert_sha256',
        ),
        migrations.RemoveField(
            model_name='server',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='server',
            name='script_out',
        ),
    ]
