# Generated by Django 4.2.18 on 2026-04-23 11:31
#
# При AUTH_USER_MODEL и «старом» графе bot: поля Server уже могут отсутствовать
# в состоянии 0001 — RemoveField даёт KeyError. Состояние не трогаем, в БД
# удаляем legacy-колонки при наличии.

from django.db import migrations

LEGACY_SERVER_COLUMNS = (
    "api_url",
    "cert_sha256",
    "is_activated",
    "script_out",
)


def _table_column_names(schema_editor, table):
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        desc = conn.introspection.get_table_description(cursor, table)
    return {row.name for row in desc}


def forwards_drop_legacy_server_columns(apps, schema_editor):
    Server = apps.get_model("bot", "Server")
    table = Server._meta.db_table
    conn = schema_editor.connection
    vendor = conn.vendor

    try:
        existing = _table_column_names(schema_editor, table)
    except Exception:
        return

    to_drop = [c for c in LEGACY_SERVER_COLUMNS if c in existing]
    if not to_drop:
        return

    qtable = conn.ops.quote_name(table)
    with conn.cursor() as cursor:
        for col in to_drop:
            qcol = conn.ops.quote_name(col)
            if vendor == "postgresql":
                cursor.execute(
                    f"ALTER TABLE {qtable} DROP COLUMN IF EXISTS {qcol}"
                )
            elif vendor == "sqlite":
                cursor.execute(f"ALTER TABLE {qtable} DROP COLUMN {qcol}")
            elif vendor == "mysql":
                cursor.execute(f"ALTER TABLE {qtable} DROP COLUMN {qcol}")
            else:
                cursor.execute(
                    f"ALTER TABLE {qtable} DROP COLUMN IF EXISTS {qcol}"
                )


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0022_sitenotification_alter_server_is_activated_vless_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunPython(
                    forwards_drop_legacy_server_columns,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
