# Generated by Django 4.2.18 on 2026-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_remove_server_api_url_remove_server_cert_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_c3celeryty_activated',
            field=models.BooleanField(default=False, editable=False, help_text='Нода Hysteria2 в панели C3 Celeryty настроена и готова к выдаче ключей.', verbose_name='C3 Celeryty'),
        ),
    ]
