# Generated by Django 4.2.18 on 2026-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_server_is_c3celeryty_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='category',
            field=models.CharField(choices=[('payment', 'Платежи'), ('bot', 'Бот Telegram'), ('celery', 'Celery / фоновые задачи'), ('web', 'Сайт / личный кабинет'), ('vpn', 'VPN / ключи / Marzban / Celerity'), ('mtproxy', 'MTProto proxy'), ('admin', 'Админка / служебное'), ('other', 'Прочее')], db_index=True, default='other', max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_c3celeryty_activated',
            field=models.BooleanField(default=False, help_text='Нода Hysteria2 в панели C3 Celeryty настроена и готова к выдаче ключей.', verbose_name='C3 Celeryty'),
        ),
    ]
