# Generated by Django 4.2.18 on 2026-05-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_logging_category_and_more'),
    ]

    operations = [

    ]
